/**
 * Movie Search Route
 *
 * Handles /movie/search?q=Title+Year URLs generated by EntityLinkedText
 * Implements database-first → TMDB search → redirect/results flow
 */

import { useRouter } from 'next/router';
import { useState, useEffect } from 'react';
import PhoneFrame from '../../components/PhoneFrame';
import SimpleSearch from '../../components/SimpleSearch';
import MediaCard from '../../components/MediaCard';
import { searchOurDatabase } from '../../lib/services/database-search';
import { searchAndCategorize, getTMDBMovieDetails } from '../../lib/services/tmdb-search';
import { flagForNuclearPromotion } from '../../lib/services/nuclear-promotion';

export default function MovieSearchPage({ searchType, query, results, error, redirectInfo }) {
  const router = useRouter();
  const [searchResults, setSearchResults] = useState([]);
  const [showSearchResults, setShowSearchResults] = useState(false);

  // Handle search results from SimpleSearch component
  const handleSearchResults = newResults => {
    setSearchResults(newResults);
    setShowSearchResults(newResults.length > 0);
  };

  const handleClearSearch = () => {
    setSearchResults([]);
    setShowSearchResults(false);
  };

  // MediaCard now handles all navigation internally with fallback logic

  // Handle TMDB movie selection and creation
  const handleTMDBMovieClick = async tmdbMovie => {
    try {
      console.log(`🎬 Creating movie from TMDB: "${tmdbMovie.title}" (ID: ${tmdbMovie.id})`);

      // Track nuclear promotion
      await flagForNuclearPromotion(tmdbMovie.id, 'search_click', {
        query: query,
        userAgent: navigator.userAgent,
      });

      // Navigate to movie page (will be created via getServerSideProps)
      router.push(`/movie/${tmdbMovie.id}`);
    } catch (error) {
      console.error('Error handling TMDB movie click:', error);
    }
  };

  if (error) {
    return (
      <PhoneFrame>
        <div style={styles.container}>
          <div style={styles.header}>
            <SimpleSearch onResults={handleSearchResults} placeholder="Search movies..." />
          </div>
          <div style={styles.errorContainer}>
            <div style={styles.errorText}>Error: {error}</div>
          </div>
        </div>
      </PhoneFrame>
    );
  }

  return (
    <PhoneFrame>
      <div style={styles.container}>
        {/* Search header */}
        <div style={styles.header}>
          <SimpleSearch
            onResults={handleSearchResults}
            placeholder="Search movies..."
            initialValue={query}
          />
        </div>

        {/* Content */}
        <div style={styles.content}>
          {showSearchResults ? (
            /* New search results from SimpleSearch */
            <div style={styles.resultsContainer}>
              <div style={styles.resultsHeader}>
                <span>
                  {searchResults.length} movie{searchResults.length !== 1 ? 's' : ''} found
                </span>
                <button onClick={handleClearSearch} style={styles.clearButton}>
                  Clear
                </button>
              </div>
              <div style={styles.movieList}>
                {searchResults.map((movie, index) => (
                  <MediaCard
                    key={`${movie.tmdb_id || movie.title}-${index}`}
                    title={movie.title}
                    year={movie.year}
                    initialSlug={movie.slug}
                    initialPoster={movie.poster_url}
                    initialStreaming={movie.streaming_data}
                    tmdbId={movie.tmdb_id}
                  />
                ))}
              </div>
            </div>
          ) : (
            /* Results from EntityLinkedText query */
            <>
              {searchType === 'multiple_matches' && (
                <div style={styles.resultsContainer}>
                  <div style={styles.resultsHeader}>
                    <span>Multiple matches for "{query}"</span>
                  </div>
                  <div style={styles.subtitle}>Select the movie you're looking for:</div>
                  <div style={styles.tmdbResults}>
                    {results.map((movie, index) => (
                      <TMDBMovieResult
                        key={movie.id}
                        movie={movie}
                        onClick={() => handleTMDBMovieClick(movie)}
                      />
                    ))}
                  </div>
                </div>
              )}

              {searchType === 'no_matches' && (
                <div style={styles.resultsContainer}>
                  <div style={styles.noResults}>
                    <h2>Movie not found</h2>
                    <p>We couldn't find "{query}" in our database or TMDB.</p>
                    <p>
                      Try adjusting the title or year, or use the search above to find similar
                      movies.
                    </p>
                  </div>
                </div>
              )}

              {searchType === 'processing' && (
                <div style={styles.resultsContainer}>
                  <div style={styles.processing}>
                    <h2>Searching for "{query}"</h2>
                    <p>Looking in our database and TMDB...</p>
                  </div>
                </div>
              )}

              {redirectInfo && (
                <div style={styles.resultsContainer}>
                  <div style={styles.redirectInfo}>
                    <h2>Redirecting...</h2>
                    <p>{redirectInfo}</p>
                  </div>
                </div>
              )}
            </>
          )}
        </div>
      </div>
    </PhoneFrame>
  );
}

/**
 * TMDB Movie Result Component
 * Shows TMDB search results that can be clicked to create movie pages
 */
function TMDBMovieResult({ movie, onClick }) {
  const year = movie.release_date ? movie.release_date.substring(0, 4) : 'Unknown';
  const posterUrl = movie.poster_path
    ? `https://image.tmdb.org/t/p/w200${movie.poster_path}`
    : '/images/placeholder-poster.jpg';

  return (
    <div style={styles.tmdbResult} onClick={() => onClick(movie)}>
      <div style={styles.tmdbPoster}>
        <img src={posterUrl} alt={`Poster for ${movie.title}`} style={styles.posterImage} />
      </div>
      <div style={styles.tmdbInfo}>
        <div style={styles.tmdbTitle}>{movie.title}</div>
        <div style={styles.tmdbYear}>({year})</div>
        {movie.overview && (
          <div style={styles.tmdbOverview}>
            {movie.overview.length > 150
              ? movie.overview.substring(0, 150) + '...'
              : movie.overview}
          </div>
        )}
        <div style={styles.tmdbClick}>Click to view this movie</div>
      </div>
    </div>
  );
}

/**
 * Server-side props: Handle the main search logic
 */
export async function getServerSideProps({ query }) {
  const searchQuery = query.q;

  if (!searchQuery) {
    return {
      props: {
        searchType: 'no_query',
        error: 'No search query provided',
      },
    };
  }

  console.log(`🔍 Movie search request: "${searchQuery}"`);

  try {
    // Step 1: Check our database first (2% coverage)
    const dbMovie = await searchOurDatabase(searchQuery);

    if (dbMovie) {
      console.log(`✅ Database match found, redirecting to /movie/${dbMovie.tmdb_id}`);

      return {
        redirect: {
          destination: `/movie/${dbMovie.tmdb_id}`,
          permanent: false,
        },
      };
    }

    // Step 2: Search TMDB (98% coverage)
    console.log(`🎬 No database match, searching TMDB...`);
    const tmdbResult = await searchAndCategorize(searchQuery);

    if (tmdbResult.type === 'single_match') {
      console.log(`✅ Single TMDB match found, redirecting to /movie/${tmdbResult.movie.id}`);

      return {
        redirect: {
          destination: `/movie/${tmdbResult.movie.id}`,
          permanent: false,
        },
      };
    }

    if (tmdbResult.type === 'multiple_matches') {
      console.log(`📋 Multiple TMDB matches found, showing results page`);

      return {
        props: {
          searchType: 'multiple_matches',
          query: searchQuery,
          results: tmdbResult.results,
        },
      };
    }

    if (tmdbResult.type === 'no_matches') {
      console.log(`❌ No TMDB matches found`);

      return {
        props: {
          searchType: 'no_matches',
          query: searchQuery,
        },
      };
    }
  } catch (error) {
    console.error('Movie search error:', error);

    return {
      props: {
        searchType: 'error',
        query: searchQuery,
        error: 'Search service temporarily unavailable',
      },
    };
  }

  // Fallback
  return {
    props: {
      searchType: 'error',
      query: searchQuery,
      error: 'Unknown error occurred',
    },
  };
}

const styles = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
    backgroundColor: '#f9fafb',
  },
  header: {
    backgroundColor: '#ffffff',
    borderBottom: '1px solid #e5e7eb',
    padding: '16px',
  },
  content: {
    flex: 1,
    overflowY: 'scroll',
    scrollbarWidth: 'none',
    msOverflowStyle: 'none',
  },
  resultsContainer: {
    padding: '16px',
  },
  resultsHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '16px',
    fontSize: '14px',
    color: '#6b7280',
  },
  subtitle: {
    fontSize: '14px',
    color: '#6b7280',
    marginBottom: '16px',
  },
  clearButton: {
    backgroundColor: '#374151',
    color: 'white',
    border: 'none',
    padding: '6px 12px',
    borderRadius: '6px',
    fontSize: '12px',
    cursor: 'pointer',
    fontFamily: 'inherit',
  },
  movieList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1px',
    backgroundColor: '#f3f4f6',
  },
  tmdbResults: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  tmdbResult: {
    display: 'flex',
    backgroundColor: 'white',
    borderRadius: '8px',
    padding: '12px',
    cursor: 'pointer',
    border: '1px solid #e5e7eb',
    transition: 'box-shadow 0.2s ease',
  },
  tmdbPoster: {
    width: '60px',
    height: '90px',
    minWidth: '60px',
    marginRight: '12px',
    borderRadius: '4px',
    overflow: 'hidden',
  },
  posterImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  tmdbInfo: {
    flex: 1,
    minWidth: 0,
  },
  tmdbTitle: {
    fontSize: '16px',
    fontWeight: '600',
    color: '#000',
    marginBottom: '2px',
  },
  tmdbYear: {
    fontSize: '14px',
    color: '#6b7280',
    marginBottom: '8px',
  },
  tmdbOverview: {
    fontSize: '14px',
    color: '#374151',
    lineHeight: '1.4',
    marginBottom: '8px',
  },
  tmdbClick: {
    fontSize: '12px',
    color: '#3b82f6',
    fontWeight: '500',
  },
  noResults: {
    textAlign: 'center',
    padding: '40px 20px',
    color: '#6b7280',
  },
  processing: {
    textAlign: 'center',
    padding: '40px 20px',
    color: '#6b7280',
  },
  redirectInfo: {
    textAlign: 'center',
    padding: '40px 20px',
    color: '#6b7280',
  },
  errorContainer: {
    padding: '40px 16px',
    textAlign: 'center',
  },
  errorText: {
    fontSize: '16px',
    color: '#dc2626',
  },
};
